export const WALLET_LIMITS_ADD_FETCH = 'WALLET_LIMITS_ADD_FETCH';
export const WALLET_LIMITS_ADD_DATA = 'WALLET_LIMITS_ADD_DATA';
export const WALLET_LIMITS_ADD_ERROR = 'WALLET_LIMITS_ADD_ERROR';

export const WALLET_LIMITS_EDIT_FETCH = 'WALLET_LIMITS_EDIT_FETCH';
export const WALLET_LIMITS_EDIT_DATA = 'WALLET_LIMITS_EDIT_DATA';
export const WALLET_LIMITS_EDIT_ERROR = 'WALLET_LIMITS_EDIT_ERROR';

export const WALLET_LIMITS_GET_FETCH = 'WALLET_LIMITS_GET_FETCH';
export const WALLET_LIMITS_GET_DATA = 'WALLET_LIMITS_GET_DATA';
export const WALLET_LIMITS_GET_ERROR = 'WALLET_LIMITS_GET_ERROR';
